### ISSUE TITLE
Doesn't work for Alfred 2.6 on OS X 10.9.5 

### ISSUE THREAD

**Issue by designingdesign** [LeEnno/alfred-firechrome#3]
Nothing happens!

**Comment by LeEnno** [comment]
Thx for reporting.

Unfortunately I run on Yosemite and have no Mavericks system to test it, so we have to track it down together, if you don't mind.

Which direction are you testing? Chrome → Firefox or Firefox → Chrome?
Launch Script Editor (find it via Alfred or in `/Applications/Utilities/`), paste the code matching your direction and paste the results here.

Code for Chrome → Firefox:

```applescript
property theURL : ""

tell application "Google Chrome"
	set theURL to URL of active tab of window 1
end tell
tell application "System Events"
	do shell script "Open -a Firefox " & theURL
end tell
```

Code for Firefox → Chrome:

```applescript
tell application "Firefox" to activate
tell application "System Events"
	keystroke "l" using command down
	keystroke "c" using command down
	delay 0.1
end tell
set theURL to the clipboard
tell application "Google Chrome"
	activate
	set myTab to make new tab at end of tabs of window 1
	set URL of myTab to theURL
end tell
```

(Remember to actually have a tab open in your start browser)

Hope we can solve this issue.

**Comment by designingdesign** [comment]
I've been testing Chrome to Firefox.
When I try to run the Chrome to Firefox code in AppleScript I get the following error:
`Expected end of line but found property.`

and this is highlighted:
![screen shot 2015-02-10 at 9 49 39 am](https://cloud.githubusercontent.com/assets/6680415/6124050/280e0348-b10a-11e4-9fa1-fc06625ee69e.png)

Doing some research it seems it's because I have [Parallels](http://stackoverflow.com/questions/22847583/applescript-expected-end-of-line-but-found-property-error-when-using-google-c) installed (even though it's not running). Following the Stackoverflow comments suggestions hasn't solved my problem. I'll report back though!

**Comment by designingdesign** [comment]
Turns out I had to disable "Share Windows Application with Mac" in Parallels Solved the issue :)

**Comment by LeEnno** [comment]
Okay, weird issue, but good to know. Thx for investigating.
